"""Content-layer prompt specifications for O19-O33.

These specifications deliberately contain no release decision.  O19-O33 are
callable by stable ID for content development and forced qualification, while
their mechanism contracts keep them out of production routing until evidence
supports a later status transition.
"""

from __future__ import annotations

from typing import Any, Dict, Iterable, Mapping, Sequence

from .base import OperatorPromptSpec


def _spec(
    operator_id: str,
    name: str,
    *,
    axes: Sequence[str],
    goal: str,
    reasoning_object: str,
    question_shape: str,
    transformation: str,
    invariants: Sequence[str],
    target_errors: Sequence[str],
    boundaries: str,
    controls: Sequence[str],
    shortcuts: str,
    tasks: Sequence[str],
    axis_tasks: Mapping[str, Sequence[str]] | None = None,
    axis_dependencies: Sequence[str] = (),
) -> OperatorPromptSpec:
    return OperatorPromptSpec(
        operator_id=operator_id,
        name=name,
        ability_axis=axes[0],
        ability_axes=tuple(axes),
        goal=goal,
        reasoning_object=reasoning_object,
        required_question_shape=question_shape,
        content_transformation=transformation,
        invariants=tuple(invariants),
        competition_structure="候选关系必须具有真实竞争性；不得由单一醒目事实、数量、标签或格式直接支配答案。",
        preserved_parent_obligations=(
            "保留父题核心业务判断和可观察事实边界",
            "保留父题允许的结论层级，不把线索升级为已确认身份、成分、角色或违法性质",
        ),
        required_reasoning_tasks=tuple(tasks),
        target_error_taxonomy=tuple(target_errors),
        excluded_error_taxonomy=("format_only_failure", "outside_knowledge_failure"),
        forbidden_shortcuts=shortcuts,
        adjacent_boundaries=boundaries,
        content_controls=tuple(controls),
        allowed_answer_shape="一个自然业务判断及开放式依据；内部答案可保存分轴结构，但题面不预拆解。",
        forbidden_answer_shape="不得把内部图、矩阵、断点、关键边、分层标签或逐步检查清单直接写进题面。",
        default_evaluation_focus=tuple(tasks),
        axis_reasoning_tasks=dict(axis_tasks or {}),
        axis_dependencies=tuple(axis_dependencies),
    )


SPECS = (
    _spec(
        "O19_multi_entity_role_binding",
        "多实体角色绑定",
        axes=("entity_binding_under_swap", "role_direction_consistency"),
        goal="在多类实体和观测节点中维持身份、关系方向与事件角色，并在绑定或角色交换后更新结论。",
        reasoning_object="实体-观测节点-关系-角色图。",
        question_shape="自然呈现同类实体、局部观测和目标关系，只询问材料对目标关系或角色支持到何种程度。",
        transformation="交换同类实体的节点绑定或事件角色；可反转目标关系方向。",
        invariants=("观测时间", "事件动作", "目标关系类型", "未变更实体事实"),
        target_errors=("entity_merge", "entity_swap_ignored", "role_direction_reversed", "local_binding_overgeneralized"),
        boundaries="O10 测事实组合证明力；O19 测事实绑定到哪个实体和角色。O29 处理多个既有绑定之间的同一性冲突。",
        controls=("角色交换正控制", "局部绑定变化但整体结论不变负控制", "实体表面标签交换控制"),
        shortcuts="不得靠姓名、编号、外观相似或角色标签编码答案，不得给出完整关系图。",
        tasks=("维持节点到实体绑定", "检查关系方向", "限制局部关系向整体事件的外推"),
    ),
    _spec(
        "O20_multistage_event_breakpoint",
        "多阶段事件链断点",
        axes=("state_transition_breakpoint", "partial_chain_boundary"),
        goal="在多阶段状态图中定位使完整事件链无法闭合的节点或边。",
        reasoning_object="带时序、实体绑定和状态前后变化的事件图。",
        question_shape="自然呈现事件节点、前后状态和必要转移，只询问目标链路是否成立及依据。",
        transformation="删除、替换或重排与目标推理相关的状态节点或转移边。",
        invariants=("未变更事件节点", "实体绑定", "目标链命题", "无关时序事实"),
        target_errors=("wrong_breakpoint", "state_transition_skipped", "temporal_edge_reversed", "partial_chain_treated_as_complete", "missing_node_filled_by_assumption"),
        boundaries="O13 测单事实移除对必要连接的影响；O20 必须维护显式多阶段状态图。O28 进一步判断跨节点整体链路闭合。",
        controls=("删除必要边正控制", "删除可选边结论不变控制", "节点表面名称交换控制"),
        shortcuts="不得显示断点标签、状态图答案或用节点数量制造难度。",
        tasks=("追踪状态前后变化", "定位失效节点或边", "区分局部成立、证据缺失和明确反证"),
    ),
    _spec(
        "O21_object_provenance_identity",
        "物品来源与同一性追踪",
        axes=("object_identity_continuity", "competing_source_resolution"),
        goal="在相似物品、遮挡、多次转移和竞争来源下判断目标物品的同一性连续。",
        reasoning_object="物品-属性-位置-转移-竞争来源链。",
        question_shape="自然给出物品属性、位置时序、转移、遮挡和竞争来源，只询问同一性支持边界。",
        transformation="调整物品绑定、遮挡后重现对象、转移关系或竞争来源。",
        invariants=("无关时序", "人员动作", "目标同一性命题", "未变更观测"),
        target_errors=("appearance_only_identity", "transfer_gap_ignored", "competing_source_ignored", "person_binding_substituted_for_object_binding", "occlusion_filled_by_assumption"),
        boundaries="O19 维护一般实体与角色绑定；O20 定位事件链断点；O21 专门追踪物品 provenance 和连续性。",
        controls=("来源连续正控制", "外观相似但来源竞争负控制", "物品标签交换控制"),
        shortcuts="不得用相似外观、同一携带者或包装标签直接确认同一物品。",
        tasks=("追踪物品转移连续性", "比较竞争来源", "识别遮挡和观测缺口"),
    ),
    _spec(
        "O22_path_topology_reachability",
        "路径拓扑与联合可达性",
        axes=("topological_reachability", "path_time_endpoint_consistency"),
        goal="联合入口、出口、路网、时间窗、通行范围和端点身份判断路径或身份连续假设。",
        reasoning_object="带时间窗和通行范围的路径图。",
        question_shape="题面明确图节点、可用边、端点、时间窗和通行范围，只询问目标路径或身份连续假设。",
        transformation="调整边可用性、端点时间窗或候选路径约束。",
        invariants=("未变更网络结构", "端点身份", "目标可达性命题", "无关路径事实"),
        target_errors=("topology_ignored", "unreachable_path_selected", "travel_window_violation", "endpoint_identity_mixed", "single_path_assumed_without_exclusion"),
        boundaries="O11 检查局部端点时序；O22 必须建立路径图并联合检查拓扑、时间窗和端点身份。",
        controls=("可达路径正控制", "拓扑可达但时间不兼容负控制", "路径名称交换控制"),
        shortcuts="不得用入口数量、路径数量或单一明显差异暗示答案。",
        tasks=("检查拓扑可达性", "检查时间窗与通行范围", "维持端点身份一致"),
    ),
    _spec(
        "O23_observation_reliability_conflict",
        "观测可靠性冲突",
        axes=("observability_boundary", "downstream_support_calibration"),
        goal="判断所谓已观察事实是否能从当前质量、视角和遮挡条件中可靠获得，并限制下游结论。",
        reasoning_object="观测声明-可见特征-质量限制-下游命题关系。",
        question_shape="自然呈现观测声明、可见特征和质量限制，只询问现有观测能支持何种下游判断。",
        transformation="调整目标观测的质量、视角、遮挡或可见特征。",
        invariants=("事件本身", "下游命题", "未变更观测", "允许的结论层级"),
        target_errors=("visibility_assumed", "similarity_treated_as_identity", "quality_limit_ignored", "observation_uncertainty_skipped", "downstream_claim_overstated"),
        boundaries="O10/O15 默认输入事实已成立；O23 测该事实能否从来源内部观测中获得。O31 测多个观测间的独立增量。",
        controls=("清晰可区分正控制", "可见但不可区分负控制", "来源名称交换控制"),
        shortcuts="不得用清晰、权威等评价标签替代具体可见特征和质量条件。",
        tasks=("判断可观察性", "判断可区分性", "校准观测限制对下游命题的影响"),
    ),
    _spec(
        "O24_multi_hypothesis_residual_ranking",
        "多假设残差排序",
        axes=("coverage_conflict_residual_ranking", "extra_assumption_cost"),
        goal="按事实覆盖、冲突、未解释残差和额外假设成本比较竞争假设。",
        reasoning_object="假设的覆盖-冲突-残差矩阵。",
        question_shape="呈现真实竞争的假设、共享事实和统一排序原则，只询问当前材料下哪个解释更可取及依据。",
        transformation="增加、替换或调整与目标排序相关的可观察 discriminator。",
        invariants=("假设定义", "共享事实集", "排序原则", "目标任务"),
        target_errors=("single_fact_dominance", "coverage_conflict_tradeoff_ignored", "residuals_not_compared", "extra_assumption_cost_ignored", "plausibility_label_substituted_for_evidence"),
        boundaries="O16 聚焦目标解释与一个相近解释的 discriminator；O24 维护竞争假设的完整覆盖-冲突-残差结构。",
        controls=("残差变化正控制", "表面变化但排序不变负控制", "假设顺序交换控制"),
        shortcuts="不得用可疑、正常、常见或候选顺序替代结构比较。",
        tasks=("比较事实覆盖", "比较冲突与残差", "比较额外假设成本"),
    ),
    _spec(
        "O25_procedural_invariant_frame",
        "程序不变量与参照系",
        axes=("reference_frame_consistency", "procedure_mapping_invariance"),
        goal="在测量、标注、记录和录入程序中维持参照系、单位、顺序依赖和记录映射。",
        reasoning_object="程序步骤-参照系-单位-记录映射不变量。",
        question_shape="自然呈现程序、参照系、单位、步骤依赖和记录映射，只询问相关测量或记录是否仍可比较。",
        transformation="调整参照系、单位、步骤顺序或记录映射。",
        invariants=("观测对象", "目标比较", "未变更步骤", "未变更测量事实"),
        target_errors=("reference_frame_mixed", "unit_inconsistency", "order_dependency_ignored", "record_mapping_shifted", "non_comparable_measurements_compared"),
        boundaries="O25 判断程序结构不变量是否被破坏，不是通过新增证据改变命题，因此不属于 O10/O12。",
        controls=("一致参照正控制", "表面重命名但映射不变负控制", "坐标或单位标签交换控制"),
        shortcuts="不得以单位名称、步骤数量或软件术语直接编码可比性答案。",
        tasks=("维持参照系", "检查单位和顺序依赖", "检查记录映射与可比性"),
    ),
    _spec(
        "O26_quantitative_threshold_propagation",
        "定量阈值与误差传播",
        axes=("uncertainty_interval_propagation", "threshold_relation"),
        goal="根据题面明示的数值、单位、区间、变换规则和阈值推导结果区间并判断门槛关系。",
        reasoning_object="带单位、不确定区间、变换规则和决策阈值的定量关系。",
        question_shape="明示公式、参数、单位、误差和阈值，只询问目标定量判断是否成立及依据。",
        transformation="调整观测值、不确定区间或门槛距离。",
        invariants=("明示公式", "单位体系", "未变更观测", "目标定量命题"),
        target_errors=("point_estimate_only", "uncertainty_not_propagated", "unit_conversion_error", "threshold_crossing_overstated", "interval_overlap_ignored"),
        boundaries="O18 选择适用基线口径；O26 在口径给定后传播误差并判断阈值关系。",
        controls=("区间完全跨阈值正控制", "点估计跨阈值但区间重叠负控制", "单位表面交换控制"),
        shortcuts="不得要求题外公式或参数，不得把计算步骤写成作答流程。",
        tasks=("换算单位", "传播不确定区间", "比较结果区间与阈值"),
    ),
    _spec(
        "O27_cross_layer_conclusion_calibration",
        "跨层结论校准",
        axes=("claim_layer_mapping", "upward_transition_legality"),
        goal="区分观察事实、证据支持、事实成立、可写结论和行动门槛，并检查合法跨层传播。",
        reasoning_object="结论层级、允许转移边和所需门槛。",
        question_shape="明示相关层级、允许规则、当前证据状态和目标层级，只询问当前变化对目标结论的影响。",
        transformation="调整低层证据状态或局部推理连接。",
        invariants=("跨层规则", "目标层级", "未变更证据", "授权门槛"),
        target_errors=("evidence_drop_treated_as_claim_false", "local_link_failure_treated_as_global_reversal", "suspicion_promoted_to_fact", "fact_support_promoted_to_action_threshold", "layer_specific_rule_ignored"),
        boundaries="O13 定位局部连接变化；O27 判断能否跨层传播。O15 测同一比较量迁移；O17 比较两套明示规则。",
        controls=("合法跨层正控制", "支持下降但上层不翻转负控制", "层级名称交换控制"),
        shortcuts="不得把层级名称、动作标签或强弱措辞直接当成传播规则。",
        tasks=("定位变化所在层级", "检查允许的跨层边", "给出最高允许结论"),
    ),
    _spec(
        "O28_multihop_chain_closure",
        "多跳链路闭合",
        axes=("cross_stage_chain_closure", "cross_node_entity_continuity"),
        goal="判断跨阶段、跨节点并可涉及实体转移的目标链路是否整体闭合。",
        reasoning_object="事件节点、必需/可选/冲突边、跨节点实体绑定、路径时间约束和局部闭合链。",
        question_shape="自然呈现可观察节点、状态、边和约束，只询问现有材料能否支持目标事件链。",
        transformation="调整链路节点状态、连接边、实体绑定、时间窗或显式路径可达性。",
        invariants=("目标事件类型", "未变更事实", "目标结论层级", "未变更实体约束"),
        target_errors=("cross_stage_link_omitted", "entity_binding_broken_across_hops", "partial_chain_treated_as_closed", "path_time_constraint_ignored", "missing_hop_filled_by_assumption"),
        boundaries="O20 定位多阶段状态断点；O28 判断跨阶段跨节点整体链路闭合。O22 以路径图可达性为主。",
        controls=("整体闭合正控制", "局部闭合但整体缺失负控制", "节点表面标签交换控制", "缺失链路与明确反证消融"),
        shortcuts="不得补造盲区节点、边、通行关系或实体转移，不得用节点数量代替链路复杂度。",
        tasks=("识别局部闭合链", "检查跨节点实体连续", "区分缺失链路与明确反证"),
        axis_dependencies=("实体连续性约束整体链路闭合",),
    ),
    _spec(
        "O29_entity_identity_conflict_resolution",
        "实体同一性冲突消解",
        axes=("conflicting_binding_resolution", "identity_claim_calibration"),
        goal="综合局部绑定、时空连续、转移缺口和冲突事实，消解实体同一性命题。",
        reasoning_object="候选实体、局部绑定、时空关系、转移缺口和冲突绑定。",
        question_shape="自然呈现真实竞争的候选实体、绑定和来源，只询问同一性能够成立、降级还是未知。",
        transformation="调整外观属性、位置、时间、转移关系或冲突绑定。",
        invariants=("实体类型", "未变更事实", "目标同一性命题", "允许结论层级"),
        target_errors=("appearance_only_identity", "conflicting_binding_ignored", "transfer_gap_ignored", "local_identity_overextended", "person_binding_substituted_for_object_binding"),
        boundaries="O19 测局部实体角色绑定；O29 处理多个绑定冲突。O21 以物品来源链为主；O23 判断观测本身可靠性。",
        controls=("冲突解除正控制", "局部连续但全程冲突负控制", "候选实体标签交换控制"),
        shortcuts="不得仅凭外观、包装、共现、携带者相同或候选数量确认同一性。",
        tasks=("汇总同一性支持", "识别冲突绑定和转移缺口", "校准同一性结论"),
    ),
    _spec(
        "O30_active_discriminative_observation",
        "主动判别观测选择",
        axes=("observation_discrimination_value", "outcome_branch_update"),
        goal="从可获得观测中选择预期最能改变竞争假设区分度的下一观测。",
        reasoning_object="竞争假设、候选观测、可能结果和假设区分矩阵。",
        question_shape="给出当前事实、可行假设和可获得观测，只询问下一步获取哪项观测最有帮助。",
        transformation="调整候选观测的可能结果、质量条件或可获得性。",
        invariants=("当前事实", "假设定义", "目标命题层级", "未变更候选观测"),
        target_errors=("most_suspicious_observation_selected", "outcome_branches_ignored", "hypothesis_coverage_not_updated", "unavailable_observation_selected", "certainty_gain_overstated"),
        boundaries="O24 排序当前假设；O30 选择下一观测。O16 使用已有 discriminator；O23 判断观测质量。",
        controls=("最有区分力观测正控制", "最可疑但低区分力负控制", "假设与观测顺序交换控制", "并列最优消融"),
        shortcuts="不得用可疑、权威、信息更多、候选顺序或不可获得手段暗示选择。",
        tasks=("比较各观测结果分支", "更新剩余可行假设", "处理并列最优或无法唯一判别"),
    ),
    _spec(
        "O31_observation_accumulation_calibration",
        "观测可靠度与累积校准",
        axes=("observation_dependency", "incremental_support_order"),
        goal="区分重复、相关和相对独立观测，判断累积观察的真实信息增量和结论上限。",
        reasoning_object="观测事件、依赖图、质量、新增信息和累积支持偏序。",
        question_shape="自然呈现观测来源、时间、视角、质量和新增特征，只询问累积支持及最高允许结论。",
        transformation="调整观测独立性、质量、时间同步或新增特征。",
        invariants=("目标事件", "目标命题", "未变更观测", "结论层级和比较口径"),
        target_errors=("repetition_counted_as_independence", "shared_source_dependency_ignored", "low_quality_repeat_overweighted", "new_feature_increment_ignored", "cumulative_support_promoted_to_certainty"),
        boundaries="O23 判断单个观测是否可用；O31 判断观测之间的独立增量。O26 处理明示数值误差，不做未授权概率。",
        controls=("独立新增特征正控制", "同源低质重复负控制", "观测顺序交换控制", "次数不变依赖变化消融"),
        shortcuts="不得用重复次数、摄像头数量、顺序或未提供的概率模型编码答案。",
        tasks=("建立观测依赖关系", "识别新增信息", "比较累积前后支持偏序和结论上限"),
    ),
    _spec(
        "O32_role_graph_critical_edge",
        "角色关系图最小边",
        axes=("directed_role_relation", "critical_edge_necessity"),
        goal="判断关系图中哪些有向边对目标角色或协同结论必要，并保留边变化后的局部结论。",
        reasoning_object="实体-观测-有向关系-候选角色图及关键、替代边。",
        question_shape="自然呈现实体和有向关系事实，只询问现有材料能否支持目标角色或协同判断。",
        transformation="交换实体绑定，删除、替换或反转目标关系边。",
        invariants=("无关动作", "无关时间", "物品来源", "目标关系类型"),
        target_errors=("critical_edge_missed", "noncritical_edge_treated_as_necessary", "role_direction_reversed", "cooccurrence_promoted_to_coordination"),
        boundaries="O19 测实体角色绑定；O32 测关系图关键边。O13 测单事实移除；O29 解决实体同一性冲突。",
        controls=("关键边变化正控制", "删除非关键边负控制", "实体标签交换控制", "关系方向消融"),
        shortcuts="不得显示关系图或关键边标签，不得用共现、标签或边数量直接编码角色。",
        tasks=("建立有向关系", "识别必要与替代边", "判断边变化后的局部和整体结论"),
    ),
    _spec(
        "O33_cross_modal_support_boundary",
        "跨模态支持边界",
        axes=("source_scope_alignment", "cross_source_fusion_ceiling"),
        goal="分别判断多个来源的支持边界，处理时间、实体、范围对齐和冲突，并给出融合结论上限。",
        reasoning_object="来源事实、范围、质量、时间对齐、实体链接、冲突和结论层级。",
        question_shape="自然呈现不同来源的观察事实和范围，只询问综合材料能支持何种目标结论。",
        transformation="调整来源覆盖范围、时间对齐、实体链接、质量或冲突事实。",
        invariants=("未变更来源事实", "目标命题", "结论层级定义", "题面明示融合规则"),
        target_errors=("source_count_treated_as_strength", "scope_mismatch_ignored", "time_alignment_ignored", "cross_source_entity_link_assumed", "conflict_silently_dropped", "fusion_promoted_beyond_evidence"),
        boundaries="O23 判断来源内部可靠性；O27 判断一般跨层传播；O33 维护跨来源支持、冲突和融合上限。O14 只检查来源授权。",
        controls=("互补来源正控制", "来源增加但上限不变负控制", "来源名称交换控制", "时间或实体错位消融"),
        shortcuts="不得用来源数量、名称、专业术语或权威等级代替范围、时间、实体和冲突检查。",
        tasks=("计算各来源单独支持边界", "检查范围时间和实体对齐", "处理冲突并确定融合上限"),
        axis_dependencies=("来源对齐是合法融合的前置条件",),
    ),
)


NEW_OPERATOR_SPECS: Dict[str, OperatorPromptSpec] = {
    spec.operator_id: spec for spec in SPECS
}
