"""Content-only prompt specifications for the O19-O33 operator expansion.

This module deliberately contains no applicability schema, payload contract,
validator, qualification state, adapter, release gate, or scoring mapping.
Those mechanisms belong to the explicitly deferred second part of the plans.
"""

from typing import Any, Dict, Optional, Sequence

from .base import OperatorPromptSpec


# Per-operator semantic economy contracts are content rules, not validator
# gates.  They intentionally name the smallest structure that must remain in
# the question while banning the characteristic way each operator expands into
# an answer scaffold.
SEMANTIC_ECONOMY_BY_OPERATOR = {
    "O19_multi_entity_role_binding": (
        "共享实体画像、时段和背景只定义一次；后续只写改变角色绑定的行为差异。",
        "保留判定所需的实体—角色—时段关系，不展开完整出场表或角色关系矩阵。",
        "不得用某一实体独占更完整叙述或总结句暗示正确绑定。",
    ),
    "O20_multistage_event_breakpoint": (
        "仅呈现目标结论依赖的阶段状态和必要承接，不枚举完整流程或所有旁支。",
        "共享起点与终局只写一次，各阶段只保留改变承接关系的差异。",
        "不得用总结句、阶段编号或更长说明标出实质断点。",
    ),
    "O21_object_provenance_identity": (
        "只保留对象来源、关键转移、遮挡和竞争来源所需的连续线索。",
        "稳定对象特征在公共题干出现一次，候选来源只写新增转移差异。",
        "不得把完整来源链或同一性结论作为某个候选的额外解释。",
    ),
    "O22_path_topology_reachability": (
        "只呈现目标可达性判断所需的节点、方向边、端点和时间窗口。",
        "共享地图背景和通行规则只写一次，不展开完整路网或全部候选路径。",
        "不得通过路径描述量、顺序或总结暗示可达结果。",
    ),
    "O23_observation_reliability_conflict": (
        "保留影响观测可靠性的可见条件与竞争来源，不重复解释其结论含义。",
        "题面以事实张力组织材料，不出现最高支持、不能直接推出等边界提示。",
        "多项观测使用相近的语气和信息负载，避免谨慎项成为唯一安全项。",
    ),
    "O24_multi_hypothesis_residual_ranking": (
        "共同事实只在题干出现一次，各假设只说明各自覆盖差异与残差线索。",
        "保留决定排序的最小竞争关系，不展示覆盖矩阵、完整解释清单或排名步骤。",
        "不得让某一假设独占完整事实并集或结论总结。",
    ),
    "O25_procedural_invariant_frame": (
        "共享程序、参照系和不变条件只写一次，版本只写实际改变的步骤或输入。",
        "保留验证不变量所需的规则和状态，不复制两套完整程序或检查表。",
        "不得在题面预告哪个步骤破坏不变量。",
    ),
    "O26_quantitative_threshold_propagation": (
        "保留单位换算、误差传播、规则阈值和结论判断实际依赖的全部数值与定义。",
        "删除不参与计算或阈值关系的装饰数据，但不得因题面较长删去必要输入。",
        "不得给出中间计算、完整公式推导或预填阈值比较结果。",
    ),
    "O27_cross_layer_conclusion_calibration": (
        "保留跨层判断所需的事实张力和竞争证据，不把层级映射写成题面提示。",
        "共享观察背景只写一次，候选判断只呈现导致层级差异的事实。",
        "题面不得询问最高支持、结论边界或哪些内容不能直接推出；这些仅供答案键处理。",
    ),
    "O28_multihop_chain_closure": (
        "只保留目标主张依赖的多跳链子图和必要连接，不展开完整路径集合。",
        "共同节点和已知事实只出现一次，每跳只补充新的承接关系。",
        "不得用链路总结或显式闭合提示替回答者完成判断。",
    ),
    "O29_entity_identity_conflict_resolution": (
        "共享实体画像只定义一次，各冲突线索只保留判定身份所需的差异。",
        "保留互相竞争且局部合理的身份事实，不展示完整排除表。",
        "不得让正确身份独占谨慎、核查或更完整的解释性语言。",
    ),
    "O30_active_discriminative_observation": (
        "保留当前竞争假设和能改变选择价值的可观测差异，不预填结果分支或更新矩阵。",
        "共享场景只写一次，候选观测只写新增信息与可行条件。",
        "不得在题面说明哪项观测最有区分力或如何更新结论。",
    ),
    "O31_observation_accumulation_calibration": (
        "共享画面内容只写一次，各观测只补充来源依赖、视角或新增特征。",
        "保留判断独立性和累积价值所需的来源关系，不复制观察全文或统计表。",
        "不得用总结句暗示哪些观测可累计或不能累计。",
    ),
    "O32_role_graph_critical_edge": (
        "只呈现目标角色结论依赖的角色节点和关键关系边，不展开完整关系图。",
        "共享角色背景只写一次，候选关系只说明方向或必要连接的差异。",
        "不得以关系描述量、节点编号或结论总结暴露关键边。",
    ),
    "O33_cross_modal_support_boundary": (
        "只呈现目标融合判断需要的各模态事实、时间/实体对齐和竞争关系。",
        "每个来源只保留新增支持，避免在结尾重复全部来源或写融合总结。",
        "题面不得提示限定范围、不能推出或答案边界；通过事实冲突让回答者自行校准。",
    ),
}


def _axis(
    name: str,
    reasoning_task: str,
    target_errors: Sequence[str],
    conclusion_boundary: str,
    content_dependencies: Sequence[str],
) -> Dict[str, Any]:
    return {
        "axis_name": name,
        "reasoning_task": reasoning_task,
        "target_errors": list(target_errors),
        "conclusion_boundary": conclusion_boundary,
        "content_dependencies": list(content_dependencies),
    }


def _spec(
    *,
    operator_id: str,
    name: str,
    ability_axis: str,
    goal: str,
    required_question_shape: str,
    avoid: str,
    evaluation_focus: Sequence[str],
    reasoning_object: str,
    transformation: str,
    invariants: Sequence[str],
    competition: str,
    parent_obligations: Sequence[str],
    reasoning_tasks: Sequence[str],
    semantic_axes: Sequence[Dict[str, Any]],
    target_errors: Sequence[str],
    excluded_errors: Sequence[str],
    shortcuts: Sequence[str],
    boundaries: Sequence[str],
    positive_controls: Sequence[str],
    negative_controls: Sequence[str],
    adjacent_controls: Sequence[str],
    surface_controls: Sequence[str],
    balance_controls: Sequence[str],
    scene_content_seeds: Optional[Dict[str, str]] = None,
) -> OperatorPromptSpec:
    return OperatorPromptSpec(
        operator_id=operator_id,
        name=name,
        ability_axis=ability_axis,
        goal=goal,
        required_question_shape=required_question_shape,
        avoid=avoid,
        default_evaluation_focus=evaluation_focus,
        reasoning_object=reasoning_object,
        content_transformation=transformation,
        invariants=invariants,
        competition_structure=competition,
        preserved_parent_obligations=parent_obligations,
        required_reasoning_tasks=reasoning_tasks,
        semantic_axes=semantic_axes,
        scene_content_seeds=dict(scene_content_seeds or {}),
        target_error_taxonomy=target_errors,
        excluded_error_taxonomy=excluded_errors,
        forbidden_shortcuts=shortcuts,
        adjacent_operator_boundaries=boundaries,
        positive_controls=positive_controls,
        conclusion_invariant_negative_controls=negative_controls,
        adjacent_operator_controls=adjacent_controls,
        surface_swap_controls=surface_controls,
        hidden_role_balance_controls=balance_controls,
        allowed_answer_shapes=(
            "一个自然业务判断，随后用题面事实解释关键关系与结论边界",
            "可以承认局部不确定性，但必须给出当前材料允许的最强结论",
        ),
        forbidden_answer_shapes=(
            "按内部语义轴、事实角色或控制类型逐项作答",
            "复述 operator 名称、目标错误标签或预设答案方向",
            "用固定表格、清单或机械步骤替代业务判断",
        ),
        semantic_economy=SEMANTIC_ECONOMY_BY_OPERATOR[operator_id],
        prompt_recipe_version="semantic_economy_structural_v1",
    )


O19_SPEC = _spec(
    operator_id="O19_multi_entity_role_binding",
    name="多实体角色绑定",
    ability_axis="multi_entity_role_binding",
    goal="在多实体、多时段和角色交换条件下，判断证据究竟绑定到哪个主体、什么角色与哪一段行为。",
    required_question_shape="给出可自然混淆的实体—行为关系，要求作出一个整体业务判断并说明最关键的绑定依据。",
    avoid="不要靠姓名相似、信息缺失或显式编号制造混淆；不要把实体表和角色答案直接列给回答者。",
    evaluation_focus=("实体是否保持区分", "角色方向是否正确", "局部证据是否被错误推广"),
    reasoning_object="带时间与行为方向的实体—角色关系图",
    transformation="把原题的单主体证据改造成可交换但不可合并的实体—角色图，并让结论依赖正确绑定。",
    invariants=("原题核心业务判断保持不变", "每项关键行为都能由题面定位到实体与时段", "干扰实体能解释部分而非全部事实"),
    competition="竞争判断共享显著行为，但在执行者、受益者、协同行为或时间归属上不同。",
    parent_obligations=("保留原题关键证据义务", "保留原结论所需的证据强度边界"),
    reasoning_tasks=("追踪实体连续性", "恢复角色方向", "把局部行为约束到对应主体", "判断交换是否改变结论"),
    semantic_axes=(
        _axis("entity_identity", "保持主体身份连续且不合并相似实体", ("entity_merge",), "结论只归于被完整绑定的实体", ("时段标记", "可区分的连续线索")),
        _axis("role_direction", "区分实施、协助、承受与受益角色", ("role_direction_error",), "角色方向不等价于共同出现", ("行为方向线索", "关系上下文")),
        _axis("swap_tracking", "追踪角色交换前后的证据归属", ("swap_ignored",), "交换后的证据不得回填到交换前主体", ("交换事件", "交换前后连续信息")),
    ),
    target_errors=("entity_merge", "entity_swap_ignored", "role_direction_reversed", "local_binding_overgeneralized"),
    excluded_errors=("单纯缺少外部知识", "只比较证据充分层级", "仅判断观察本身是否可靠"),
    shortcuts=("按出场顺序默认角色", "把共同出现当作共同行为", "用单个显著动作替代全程绑定"),
    boundaries=("O10 关注证据充分性而非实体绑定", "O21 关注对象来源与同一性而非主体角色图", "O29 关注冲突身份线索的裁决"),
    positive_controls=("仅改变关键行为的实体归属时，合理结论应随之改变",),
    negative_controls=("交换非关键角色或无关实体标签时，结论不应改变",),
    adjacent_controls=("保持证据强度相同，仅让实体绑定成为决定因素",),
    surface_controls=("替换姓名、服装、位置等表面线索不得直接提示正确绑定",),
    balance_controls=("正确与干扰实体轮换承担先出现、信息多和措辞显著的角色",),
)

O20_SPEC = _spec(
    operator_id="O20_multistage_event_breakpoint",
    name="多阶段事件链断点",
    ability_axis="multistage_event_chain_breakpoint",
    goal="要求模型在多阶段事件或状态转移链中找到真正阻断整体结论的断点及其后果。",
    required_question_shape="以自然叙事给出跨阶段状态变化，要求判断整体链是否成立并解释决定性断点。",
    avoid="不要用显式流程题、节点编号或提示“找断点”；不要把阶段数量本身当作难度。",
    evaluation_focus=("状态转移是否连续", "断点定位是否正确", "局部成立是否被误当整体成立"),
    reasoning_object="事件—状态转移图及其必要连接",
    transformation="把单步判断扩展为具有局部成立与关键失效并存的事件链。",
    invariants=("每个关键转移都有题面依据", "局部链能迷惑但不足以闭合整体结论", "断点与业务后果存在明确关系"),
    competition="竞争判断分别由局部顺畅链和完整闭合链支持，表面接近但整体效力不同。",
    parent_obligations=("保留原题终局结论", "保留原题关键事实的时序约束"),
    reasoning_tasks=("恢复事件顺序", "检查状态转移条件", "定位首个实质断点", "判断断点后的结论可否继续传递"),
    semantic_axes=(
        _axis("stage_continuity", "检查相邻阶段状态是否能合法承接", ("transition_assumed",), "缺失承接不得由结果反推", ("阶段状态", "承接条件")),
        _axis("breakpoint_effect", "区分形式缺口与足以阻断结论的实质断点", ("wrong_breakpoint",), "只有破坏必要连接的断点改变整体结论", ("必要连接", "后续依赖")),
        _axis("local_global", "区分局部片段成立与全链闭合", ("local_chain_overgeneralized",), "局部成功不能替代完整链路", ("局部链", "终局要求")),
    ),
    target_errors=("wrong_breakpoint", "state_transition_skipped", "temporal_edge_reversed", "partial_chain_treated_as_complete", "missing_node_filled_by_assumption"),
    excluded_errors=("仅做路径可达性", "只找最小新增否决事实", "纯信息闭包缺口"),
    shortcuts=("从终局倒推中间状态", "把最后出现的异常当断点", "忽略断点后的依赖传播"),
    boundaries=("O13 是最小失效事实，不要求恢复完整多阶段链", "O28 强调多跳链整体闭合", "O22 强调路径拓扑与窗口"),
    positive_controls=("修复实质断点后，整体链结论应能够重新成立",),
    negative_controls=("改变不参与必要连接的旁支事件时，整体结论不应改变",),
    adjacent_controls=("保留同一事件事实，让推理负担落在状态转移而非路径枚举",),
    surface_controls=("阶段名称、叙述顺序和篇幅不得泄露断点位置",),
    balance_controls=("断点在链中位置、显著程度及前后信息量保持均衡变化",),
)

O21_SPEC = _spec(
    operator_id="O21_object_provenance_identity",
    name="对象来源与同一性追踪",
    ability_axis="object_provenance_identity",
    goal="在转移、遮挡、重现和竞争来源条件下判断当前对象是否仍可绑定到原对象或特定来源。",
    required_question_shape="自然描述对象流转与可见性变化，要求判断来源或同一性主张是否成立并说明依据。",
    avoid="不要靠唯一编号直接给答案；不要把对象来源写成显式追踪表。",
    evaluation_focus=("来源链是否闭合", "对象同一性是否过度推定", "竞争来源是否被排除"),
    reasoning_object="对象的来源—转移—重现链",
    transformation="为原题对象加入可解释的转移缺口与竞争来源，使结论依赖来源链而非外观相似。",
    invariants=("对象特征与转移事实均来自题面", "竞争来源具有局部可解释性", "同一性结论强度与链路完整性匹配"),
    competition="同外观、近时段或共位置的对象分别来自不同来源链，只有完整链支持同一性。",
    parent_obligations=("保留原题对象相关业务结论", "保留原题对身份确认强度的要求"),
    reasoning_tasks=("追踪保管或转移链", "识别遮挡区间", "比较竞争来源", "校准同一性结论"),
    semantic_axes=(
        _axis("provenance_chain", "恢复对象来源与流转", ("source_chain_break_ignored",), "来源缺口限制可确认程度", ("来源事件", "转移记录")),
        _axis("identity_persistence", "判断遮挡或重现前后是否仍为同一对象", ("appearance_identity_substitution",), "相似外观不是同一性充分条件", ("稳定特征", "连续性证据")),
        _axis("competing_source", "比较可到达当前位置的其他来源", ("competing_source_ignored",), "未排除竞争来源时不得作唯一归属", ("竞争来源", "到达条件")),
    ),
    target_errors=("appearance_only_identity", "transfer_gap_ignored", "competing_source_ignored", "person_binding_substituted_for_object_binding", "occlusion_filled_by_assumption"),
    excluded_errors=("主体角色方向错误", "观察质量本身不可靠", "纯路径可达性"),
    shortcuts=("把外观相似当唯一身份", "用临近时间替代连续转移", "忽略可行竞争来源"),
    boundaries=("O19 追踪主体角色绑定", "O20 追踪事件状态链", "O29 裁决相互冲突的实体身份线索"),
    positive_controls=("补足关键转移证据后，同一性结论可以增强",),
    negative_controls=("改变无识别力的颜色或描述顺序时，结论不应改变",),
    adjacent_controls=("保持主体关系简单，让来源与对象连续性承担核心难度",),
    surface_controls=("外观显著度、命名与叙述篇幅不能与真实来源绑定",),
    balance_controls=("正确来源与竞争来源轮换承担更早出现、更多描述和更近位置",),
)

O22_SPEC = _spec(
    operator_id="O22_path_topology_reachability",
    name="路径拓扑联合可达性",
    ability_axis="path_topology_joint_reachability",
    goal="联合检查路径拓扑、端点、时间窗口与通行约束，判断候选路径是否真正可达。",
    required_question_shape="给出自然场景中的候选路径与时空约束，要求判断关键主张是否可行并说明决定性约束。",
    avoid="不要变成复杂图算法或按边逐项计算；不要用路径数量制造难度。",
    evaluation_focus=("拓扑是否连通", "时间窗是否兼容", "端点和方向约束是否同时满足"),
    reasoning_object="受时空与方向约束的路径拓扑",
    transformation="把单一时间或位置线索扩展为需要联合满足拓扑、端点和窗口的可达性判断。",
    invariants=("题面提供判断所需的路径与窗口事实", "候选路径至少满足部分约束", "结论取决于约束联合而非单一显著边"),
    competition="竞争路径在距离、时间或连通性上各有优势，但只有联合满足者可达。",
    parent_obligations=("保留原题时空主张", "保留原题不可观察区间的边界"),
    reasoning_tasks=("恢复拓扑连接", "核对方向和端点", "叠加时间窗口", "判断联合可达性"),
    semantic_axes=(
        _axis("topology", "检查节点与边是否真实连通", ("false_connectivity",), "表面邻近不等于拓扑连通", ("节点关系", "边方向")),
        _axis("window_compatibility", "检查通行与观测窗口是否兼容", ("window_ignored",), "路径存在不代表窗口内可完成", ("时间窗", "耗时或开放条件")),
        _axis("endpoint_binding", "核对路径端点与目标主体或地点", ("endpoint_mismatch",), "到达相邻端点不等于到达目标", ("端点标识", "主体位置")),
    ),
    target_errors=("topology_ignored", "unreachable_path_selected", "travel_window_violation", "endpoint_identity_mixed", "single_path_assumed_without_exclusion"),
    excluded_errors=("纯粹未观测状态补设", "多阶段状态断点", "数值误差传播"),
    shortcuts=("按直线距离判断可达", "忽略单向或封闭边", "只验证一条时空约束"),
    boundaries=("O11 聚焦不可见状态归因", "O20 聚焦状态转移断点", "O28 聚焦跨节点多跳链整体闭合"),
    positive_controls=("改变决定性边或窗口后，可达性结论应相应改变",),
    negative_controls=("改变不在候选路径上的旁支边时，结论不应改变",),
    adjacent_controls=("避免引入额外事件因果，使判断集中于联合可达性",),
    surface_controls=("路径名称、绘制顺序和叙述长短不得暗示可行性",),
    balance_controls=("可行与不可行路径在距离、描述量和显著线索上保持平衡",),
)

O23_SPEC = _spec(
    operator_id="O23_observation_reliability_conflict",
    name="观测可靠性冲突",
    ability_axis="observation_reliability_conflict",
    goal="先判断观测事实本身的可见性、清晰度、来源一致性与可靠边界，再决定其能支持什么结论。",
    required_question_shape="给出存在质量限制或来源冲突的观测，要求作出业务判断并说明观测可支持的范围。",
    avoid="不要把来源标签直接等同可靠性；不要仅比较证据数量或权威措辞。",
    evaluation_focus=("观测是否可采信", "冲突是否得到解释", "结论是否超出可靠观测范围"),
    reasoning_object="带质量与来源约束的观测事实",
    transformation="把默认可信的原题观测改造成局部可靠、局部冲突且结论边界不同的观测集合。",
    invariants=("质量限制有题面依据", "冲突来源均可能解释部分现象", "可靠性判断先于事实推断"),
    competition="竞争判断分别把观测当完整事实或受限事实，差异来自可靠边界而非结论偏好。",
    parent_obligations=("保留原题所需事实类型", "保留结论强度与证据强度的对应"),
    reasoning_tasks=("识别可见性限制", "比较来源条件", "解释冲突", "限定可采信事实"),
    semantic_axes=(
        _axis("visibility_quality", "评估遮挡、清晰度与采样条件", ("quality_limit_ignored",), "不可辨细节不得升级为确定事实", ("观测条件", "可辨范围")),
        _axis("source_conflict", "判断冲突是否由来源范围或时段差异解释", ("source_conflict_flattened",), "冲突未解释时结论应保留", ("来源范围", "时间对应")),
        _axis("reliability_to_claim", "把可靠观测映射到允许的结论层级", ("reliability_overclaim",), "局部可靠仅支持局部结论", ("可靠事实", "结论门槛")),
    ),
    target_errors=("visibility_assumed", "similarity_treated_as_identity", "quality_limit_ignored", "observation_uncertainty_skipped", "downstream_claim_overstated"),
    excluded_errors=("证据充分性层级错误", "对象同一性链缺口", "多假设残差排序"),
    shortcuts=("默认清晰画面无误", "按来源权威性直接裁决", "用多数一致替代质量分析"),
    boundaries=("O10 默认事实可用后比较充分性", "O15 改变事实值而非观测可靠性", "O31 判断观测累积后的增量"),
    positive_controls=("改善决定性观测条件或解释冲突后，结论强度可以提升",),
    negative_controls=("增加同一受限来源的重复描述时，结论不应自动增强",),
    adjacent_controls=("保持对象绑定稳定，避免滑向对象同一性问题",),
    surface_controls=("来源名称、设备品牌与专业措辞不得替代可靠性事实",),
    balance_controls=("可靠与受限来源轮换承担更详细、更早或更肯定的表述",),
)

O24_SPEC = _spec(
    operator_id="O24_multi_hypothesis_residual_ranking",
    name="多假设残差排序",
    ability_axis="multi_hypothesis_residual_ranking",
    goal="比较候选解释对事实的覆盖、冲突、残差与额外假设成本，给出校准后的解释排序。",
    required_question_shape="自然呈现可竞争的业务解释与事实，要求判断当前最合理解释及仍未解决的残差。",
    avoid="不要要求固定数量的假设或形式化打分表；不要让某个解释靠标签或篇幅明显胜出。",
    evaluation_focus=("事实覆盖是否完整", "关键冲突是否被识别", "残差与额外假设成本是否进入排序"),
    reasoning_object="候选假设—事实覆盖与残差关系",
    transformation="把原题单一解释改造成各自覆盖部分事实、留下不同关键残差的竞争解释。",
    invariants=("候选解释均有真实支持", "材料包含有区分力的残差", "排序依据来自题面而非外部先验"),
    competition="解释之间在覆盖面、关键冲突和补充假设成本上交叉占优。",
    parent_obligations=("保留原题关键现象", "保留原题结论的不确定性边界"),
    reasoning_tasks=("匹配解释与事实", "识别关键冲突", "评估残差", "控制额外假设成本"),
    semantic_axes=(
        _axis("coverage", "比较解释能自然覆盖的事实", ("salient_fact_only",), "覆盖显著事实不等于覆盖关键事实", ("事实集合", "解释机制")),
        _axis("conflict_residual", "定位解释无法容纳的关键事实", ("critical_residual_ignored",), "未解决关键残差限制排序", ("冲突事实", "残差影响")),
        _axis("assumption_cost", "识别维持解释所需的额外补设", ("assumption_cost_ignored",), "依赖更多未给定补设的解释应降权", ("题面事实", "必要补设")),
    ),
    target_errors=("single_fact_dominance", "coverage_conflict_tradeoff_ignored", "residuals_not_compared", "extra_assumption_cost_ignored", "plausibility_label_substituted_for_evidence"),
    excluded_errors=("下一步观测选择", "观察可靠性冲突", "接近替代解释仅导致正常化"),
    shortcuts=("按解释名称先验排序", "只数支持事实", "忽略解释所需的题外补设"),
    boundaries=("O16 关注接近替代解释是否使异常正常化", "O30 选择未来判别观测", "O23 先判断观测是否可靠"),
    positive_controls=("加入能区分关键残差的事实后，解释排序应可能改变",),
    negative_controls=("增加被各解释同样覆盖的事实时，排序不应改变",),
    adjacent_controls=("所有事实先视为可靠，避免把难度转移到 O23",),
    surface_controls=("假设名称、顺序、篇幅和专业程度不得与正确排序绑定",),
    balance_controls=("优势解释轮换承担更简短、更复杂或较晚出现的表面角色",),
)

O25_SPEC = _spec(
    operator_id="O25_procedural_invariant_frame",
    name="程序不变量与参照系一致性",
    ability_axis="procedural_invariant_reference_frame",
    goal="在记录映射、单位、参照系和步骤依赖变化中保持程序不变量，判断结果是否仍可比较或成立。",
    required_question_shape="给出自然业务流程及参照变化，要求判断结果是否有效并说明破坏或保持了什么关键一致性。",
    avoid="不要写成操作手册复述或纯单位换算；不要显式要求逐步检查。",
    evaluation_focus=("参照系是否一致", "步骤依赖是否保持", "记录与对象映射是否正确"),
    reasoning_object="程序步骤、记录映射与参照系中的不变量",
    transformation="在原题流程中加入看似合理的参照、单位、顺序或映射变化，使结论依赖不变量是否保持。",
    invariants=("题面说明必要程序事实", "表面流程完整不保证语义可比", "改变非关键表述不影响判断"),
    competition="竞争判断都能复述流程，但只有一个保持对象映射、参照系与依赖关系。",
    parent_obligations=("保留原题业务结果", "保留原流程必须满足的实质条件"),
    reasoning_tasks=("识别程序不变量", "统一参照系与单位", "检查步骤依赖", "验证记录映射"),
    semantic_axes=(
        _axis("reference_frame", "统一观察方向、坐标或统计参照", ("reference_frame_mismatch",), "参照不同的结果不能直接比较", ("参照说明", "转换关系")),
        _axis("procedure_order", "检查关键步骤的前置依赖", ("order_dependency_ignored",), "形式完成但依赖倒置时结果无效", ("步骤事件", "依赖条件")),
        _axis("record_mapping", "保持记录、对象与测量值的对应", ("record_object_misbinding",), "映射错误不能由数值合理性修复", ("对象标识", "记录链")),
    ),
    target_errors=("reference_frame_mixed", "unit_inconsistency", "order_dependency_ignored", "record_mapping_shifted", "non_comparable_measurements_compared"),
    excluded_errors=("纯证据充分性", "纯数学误差传播", "实体行为角色交换"),
    shortcuts=("只看最终数值合理", "默认同名字段可比较", "把步骤齐全当作程序有效"),
    boundaries=("O10 不检查程序参照", "O12 检查共同必要事实而非程序不变量", "O26 计算误差与阈值传播"),
    positive_controls=("恢复关键映射或参照转换后，结果有效性应改变",),
    negative_controls=("更换不影响映射的记录格式时，结论不应改变",),
    adjacent_controls=("弱化数值计算负担，让不变量而非算术决定结论",),
    surface_controls=("字段名、单位写法和步骤编号不得直接标示错误",),
    balance_controls=("有效与无效流程轮换拥有更整齐格式、更完整措辞和更熟悉单位",),
)

O26_SPEC = _spec(
    operator_id="O26_quantitative_threshold_propagation",
    name="定量阈值与误差传播",
    ability_axis="quantitative_threshold_error_propagation",
    goal="依据题面给定的公式、单位、区间和误差关系，判断结果区间是否跨越业务阈值及结论能否保持。",
    required_question_shape="给出业务量、转换或误差范围以及明确关系，要求作出阈值判断并解释不确定性如何传播。",
    avoid="不要依赖题外公式或复杂计算量；不要把固定数字数量当作难度。",
    evaluation_focus=("单位与公式是否正确", "误差区间是否传播", "阈值结论是否校准"),
    reasoning_object="带单位和不确定区间的定量推导链",
    transformation="把原题点估计改造成需要传播区间、容差或转换误差的阈值判断。",
    invariants=("所需公式由题面给出或属直接算术", "单位可由题面统一", "结论依赖区间与阈值关系而非计算繁琐度"),
    competition="竞争判断的点估计相近，但在误差方向、单位或阈值跨越上不同。",
    parent_obligations=("保留原题业务阈值含义", "保留原题数值证据与结论方向"),
    reasoning_tasks=("统一单位", "按给定关系传播误差", "形成结果区间", "比较区间与阈值"),
    semantic_axes=(
        _axis("unit_formula", "选择题面给定的正确单位与关系", ("unit_conversion_error",), "单位未统一的数值不可直接入阈值", ("单位定义", "给定公式")),
        _axis("error_propagation", "传播输入误差或容差到结果", ("point_estimate_substitution",), "点估计不能替代结果区间", ("输入区间", "传播关系")),
        _axis("threshold_crossing", "判断区间相对阈值的位置", ("threshold_crossing_ignored",), "跨阈值时不得给无保留的单向结论", ("结果区间", "业务阈值")),
    ),
    target_errors=("point_estimate_only", "uncertainty_not_propagated", "unit_conversion_error", "threshold_crossing_overstated", "interval_overlap_ignored"),
    excluded_errors=("程序步骤映射错误", "单变量反事实门槛迁移", "基线范围错配"),
    shortcuts=("只算中心值", "忽略最不利误差方向", "按数值大小猜单位"),
    boundaries=("O18 检查基线口径", "O15 检查单变量变化后的定性门槛", "O25 检查程序参照与映射"),
    positive_controls=("收窄决定性误差使区间不再跨阈值时，结论应可增强",),
    negative_controls=("改变不进入公式的旁支数值时，结论不应改变",),
    adjacent_controls=("题面给足计算关系，避免外部知识或程序不变量成为核心",),
    surface_controls=("数值精度、位数、排列和单位熟悉度不得泄露结论",),
    balance_controls=("阈值两侧样例轮换拥有更整齐数值、更短计算链和更熟悉单位",),
)

O27_SPEC = _spec(
    operator_id="O27_cross_layer_conclusion_calibration",
    name="跨层结论校准",
    ability_axis="cross_layer_conclusion_calibration",
    goal="沿观测、支持、事实、可写结论与行动层传递证据效力，控制局部变化能否跨层改变最终表述。",
    required_question_shape="给出证据与业务规则，要求形成一个可写或可行动的结论并说明其边界。",
    avoid="不要把层级名称和答案模板写进题面；不要要求分层列出。",
    evaluation_focus=("证据效力是否跨层越级", "局部失效是否被正确传播", "结论措辞与行动是否匹配"),
    reasoning_object="从观测到业务行动的结论传导链",
    transformation="把原题单层判断扩展为跨层效力传导，使局部支持变化可能限制但不必然翻转终局结论。",
    invariants=("各层所需规则由题面提供", "局部证据变化的影响范围可判断", "最终表述不得强于最弱必要层"),
    competition="竞争结论共享事实基础，但在可写强度、保留措辞或行动门槛上不同。",
    parent_obligations=("保留原题事实判断", "保留原题业务行动或表述边界"),
    reasoning_tasks=("区分观测与事实", "传递支持效力", "校准可写结论", "核对行动门槛"),
    semantic_axes=(
        _axis("support_to_fact", "判断支持材料能否升级为事实", ("support_fact_collapse",), "支持不充分时只能保留事实判断", ("支持条件", "事实门槛")),
        _axis("fact_to_statement", "把事实强度映射到可写措辞", ("statement_overclaim",), "措辞不得超过事实确认程度", ("事实结论", "表述规则")),
        _axis("statement_to_action", "区分可写结论与可执行动作", ("action_layer_jump",), "满足表述条件不自动满足行动条件", ("行动规则", "门槛事实")),
    ),
    target_errors=("evidence_drop_treated_as_claim_false", "local_link_failure_treated_as_global_reversal", "suspicion_promoted_to_fact", "fact_support_promoted_to_action_threshold", "layer_specific_rule_ignored"),
    excluded_errors=("仅比较事实与行动两套门槛", "纯多阶段事件链", "只找最小否决事实"),
    shortcuts=("把支持材料直接写成事实", "局部证据失效就翻转所有层", "用保守措辞掩盖错误传导"),
    boundaries=("O17 聚焦事实与行动两套规则", "O13 聚焦最小失效连接", "O33 聚焦跨模态材料的支持上界"),
    positive_controls=("改变必要层的证据效力后，下游允许结论应相应改变",),
    negative_controls=("改变不参与最终结论的旁支支持时，终局不应改变",),
    adjacent_controls=("明确层间业务规则，避免题目退化为信息闭包问题",),
    surface_controls=("措辞强弱、层级顺序和段落位置不得直接提示正确答案",),
    balance_controls=("正确与过强结论轮换承担更专业、更保守或更简短的表面形式",),
)

O28_SPEC = _spec(
    operator_id="O28_multihop_chain_closure",
    name="多跳链路闭合",
    ability_axis="multihop_chain_closure",
    goal="跨阶段、节点、实体和路径约束检查一条业务链是否整体闭合，而非被局部连通片段误导。",
    required_question_shape="用自然业务材料呈现跨节点链路，要求判断最终主张是否成立并说明关键闭合依据。",
    avoid="不要用节点数量、显式链路表或固定跳数制造难度；不要提示逐跳验证。",
    evaluation_focus=("跨节点绑定是否连续", "局部链是否被误当完整链", "端点与终局要求是否闭合"),
    reasoning_object="跨实体、事件与路径条件的多跳链",
    transformation="把原题局部证据扩展为需跨节点承接的整体链，并加入局部成立但全链不闭合的近邻。",
    invariants=("每个必要跳转都有题面事实", "局部链具有真实解释力", "整体结论只能由全链闭合支持"),
    competition="竞争判断分别依赖局部高置信片段和跨节点完整链。",
    parent_obligations=("保留原题终局业务主张", "保留原题实体与时空约束"),
    reasoning_tasks=("连接跨节点事实", "保持实体与状态连续", "核对路径和端点", "判断整体闭合"),
    semantic_axes=(
        _axis("cross_node_binding", "保持相邻跳之间实体与状态承接", ("hop_binding_break",), "任一必要承接失效限制整体链", ("节点事实", "承接标识")),
        _axis("local_global_closure", "区分局部闭合与终局闭合", ("partial_chain_as_full",), "局部完整不得替代全链完整", ("局部路径", "终局条件")),
        _axis("joint_constraints", "联合应用时空与路径条件", ("constraint_fragmentation",), "分散满足不等于同一链联合满足", ("路径条件", "时间和端点")),
    ),
    target_errors=("cross_stage_link_omitted", "entity_binding_broken_across_hops", "partial_chain_treated_as_closed", "path_time_constraint_ignored", "missing_hop_filled_by_assumption"),
    excluded_errors=("单一事件断点", "单纯路径拓扑", "实体角色图"),
    shortcuts=("拼接来自不同实体的局部链", "从终局反推缺失跳转", "只核对最显著的中间节点"),
    boundaries=("O20 重点是状态链断点", "O22 重点是路径联合可达", "O11 重点是不可观测状态"),
    positive_controls=("补足唯一缺失的必要承接后，整体闭合判断应改变",),
    negative_controls=("改变不在主链上的旁支节点时，结论不应改变",),
    adjacent_controls=("保持单个跳转简单，让跨跳绑定承担难度",),
    surface_controls=("节点顺序、篇幅与命名不能映射到链路效力",),
    balance_controls=("完整与不完整链轮换拥有更顺畅叙事、更少节点和更显著终点",),
)

O29_SPEC = _spec(
    operator_id="O29_entity_identity_conflict_resolution",
    name="实体同一性冲突消解",
    ability_axis="entity_identity_conflict_resolution",
    goal="在身份连续、局部匹配和冲突绑定线索并存时，裁决哪些记录或行为属于同一实体。",
    required_question_shape="自然呈现相互支持又冲突的身份线索，要求作出归属判断并说明冲突如何影响结论。",
    avoid="不要依赖唯一标识符或外部身份知识；不要把身份线索逐项分类给回答者。",
    evaluation_focus=("冲突线索是否被显式权衡", "局部匹配是否被过度推广", "归属强度是否校准"),
    reasoning_object="具有冲突边的实体身份图",
    transformation="把原题确定身份改造成局部相似、连续性证据和排他冲突共同作用的身份裁决。",
    invariants=("冲突与连续性事实均在题面", "局部相似不能自动压过排他冲突", "归属强度随证据完整度变化"),
    competition="候选身份各自拥有匹配线索，但在连续性或排他冲突上不同。",
    parent_obligations=("保留原题实体相关结论", "保留原题对身份确认的业务门槛"),
    reasoning_tasks=("聚合身份线索", "识别排他冲突", "检查局部与全程连续性", "校准归属"),
    semantic_axes=(
        _axis("identity_continuity", "检查跨时段身份连续性", ("continuity_gap_ignored",), "局部一致不能填补关键连续性缺口", ("时段记录", "连续线索")),
        _axis("conflict_resolution", "权衡支持线索与排他冲突", ("conflict_suppressed",), "未解释的排他冲突限制唯一归属", ("支持线索", "冲突线索")),
        _axis("binding_scope", "限制局部绑定的适用范围", ("local_binding_globalized",), "局部片段归属不能覆盖全程", ("局部事件", "全程主张")),
    ),
    target_errors=("appearance_only_identity", "conflicting_binding_ignored", "transfer_gap_ignored", "local_identity_overextended", "person_binding_substituted_for_object_binding"),
    excluded_errors=("主体行为角色方向", "物品来源流转", "观测质量可靠性"),
    shortcuts=("按最多匹配线索投票", "忽略排他时间冲突", "把同位置当同实体"),
    boundaries=("O19 绑定主体与行为角色", "O21 追踪对象来源", "O23 判断观测本身是否可靠"),
    positive_controls=("解除决定性身份冲突后，唯一归属结论可以增强",),
    negative_controls=("增加不具排他性的表面相似时，归属不应自动增强",),
    adjacent_controls=("使各观测来源本身可靠，避免滑向 O23",),
    surface_controls=("名称、位置、出现顺序和描述量不得与正确身份绑定",),
    balance_controls=("正确身份轮换拥有较少线索、更晚出现或较弱表面相似",),
)

O30_SPEC = _spec(
    operator_id="O30_active_discriminative_observation",
    name="主动判别观测选择",
    ability_axis="active_discriminative_observation",
    goal="在当前证据无法区分竞争解释时，选择最能改变解释排序或排除分支的下一项可行观测。",
    required_question_shape="给出当前竞争解释与可执行观测条件，要求判断下一步最有判别力的观测及理由。",
    avoid="不要要求列观测清单或固定候选数量；不要把成本最低或信息最多直接等同判别力。",
    evaluation_focus=("观测能否区分竞争解释", "结果分支是否会改变判断", "可行性与代价是否合理"),
    reasoning_object="竞争解释与未来观测结果之间的判别关系",
    transformation="把原题的静态解释判断改造成选择下一项能区分关键分支的观测。",
    invariants=("候选观测均可由场景执行", "材料包含只重复现有信息的观测", "判别价值由不同结果对解释的影响决定"),
    competition="观测之间在易得、信息量和真正区分力上交叉占优。",
    parent_obligations=("保留原题竞争解释", "保留原题当前不确定性"),
    reasoning_tasks=("识别关键分歧", "预测观测结果分支", "比较判别力", "考虑可行性与代价"),
    semantic_axes=(
        _axis("disagreement_target", "定位解释真正分歧的可观测后果", ("wrong_disagreement_target",), "观测必须触及关键分歧", ("竞争解释", "差异预测")),
        _axis("outcome_branching", "判断不同结果能否改变解释排序", ("non_discriminative_observation",), "无论结果如何都不改变判断的观测价值有限", ("候选观测", "结果分支")),
        _axis("feasibility_cost", "在判别力成立后考虑可执行性与代价", ("information_volume_shortcut",), "信息多不等于可行且有区分力", ("执行条件", "成本限制")),
    ),
    target_errors=("most_suspicious_observation_selected", "outcome_branches_ignored", "hypothesis_coverage_not_updated", "unavailable_observation_selected", "certainty_gain_overstated"),
    excluded_errors=("当前多假设排序", "观测可靠性评估", "重复观测累积"),
    shortcuts=("选择最容易得到的观测", "选择信息字段最多的观测", "直接重复当前最支持的证据"),
    boundaries=("O24 排序当前解释", "O16 判断接近替代解释", "O23 判断既有观测可靠性"),
    positive_controls=("改变解释的关键分歧后，最佳下一观测应相应变化",),
    negative_controls=("加入不会改变任何解释预测的观测时，选择不应改变",),
    adjacent_controls=("当前解释排序保持接近，让未来判别而非静态优劣决定答案",),
    surface_controls=("观测选项的顺序、成本措辞和技术程度不得泄露判别力",),
    balance_controls=("最佳观测轮换承担更高成本、更短描述或较不显眼的表面角色",),
    scene_content_seeds={
        "笑气": "区分普通往返、存放补货和二次分装，选择最有区分力的可见变化。",
        "电动车": "区分偶然共现、同行和协同，比较同步、等待、汇合或独立离场的判别力。",
        "涉黄": "区分普通住户、接送和看管关系，选择能区分重复关系节点的观测。",
        "拉车门": "区分找车、误触和逐车试探，比较连续动作、目标选择或离场路径。",
    },
)

O31_SPEC = _spec(
    operator_id="O31_observation_accumulation_calibration",
    name="观测可靠度与累积校准",
    ability_axis="observation_accumulation_calibration",
    goal="区分独立增量、同源重复与依赖传播，校准多次观测累积后证据究竟增强了多少。",
    required_question_shape="自然呈现连续或多来源观测，要求判断累计证据能支持到什么程度并说明依赖关系。",
    avoid="不要虚构精确概率或固定观测次数；不要把重复次数直接当置信度。",
    evaluation_focus=("观测是否独立", "重复是否提供增量", "累积后的结论强度是否校准"),
    reasoning_object="具有来源依赖的观测累积关系",
    transformation="把原题单次观测扩展为独立、重复和派生观测混合的证据累积。",
    invariants=("来源依赖可由题面判断", "不要求未给定的概率模型", "结论强度只随真实新增信息提升"),
    competition="观测集合在数量上接近或相反，但独立信息增量不同。",
    parent_obligations=("保留原题观测结论", "保留原题证据强度边界"),
    reasoning_tasks=("识别观测来源", "判断依赖或重复", "提取独立增量", "校准累计结论"),
    semantic_axes=(
        _axis("source_dependency", "判断观测是否来自同一底层来源", ("dependent_as_independent",), "同源派生不能重复计权", ("来源链", "生成关系")),
        _axis("incremental_information", "识别新观测带来的新增区分信息", ("repeat_as_increment",), "重复同一特征不等于新增支持", ("观测内容", "已有信息")),
        _axis("accumulated_strength", "把真实增量映射到结论强度", ("accumulation_overclaim",), "无精确模型时只作有依据的定性校准", ("独立增量", "结论门槛")),
    ),
    target_errors=("repetition_counted_as_independence", "shared_source_dependency_ignored", "low_quality_repeat_overweighted", "new_feature_increment_ignored", "cumulative_support_promoted_to_certainty"),
    excluded_errors=("单次观测可靠性", "未来观测选择", "定量误差传播"),
    shortcuts=("按观测条数加权", "把不同表述当独立来源", "虚构概率提升"),
    boundaries=("O23 判断单项观测是否可靠", "O30 选择下一项判别观测", "O26 处理给定的定量误差关系"),
    positive_controls=("加入真正独立且有区分力的观测后，结论强度应可提升",),
    negative_controls=("复制、转述或同源派生观测时，结论强度不应提升",),
    adjacent_controls=("避免要求数值概率，保持在可验证的依赖与增量判断",),
    surface_controls=("观测数量、来源名称和重复措辞不得直接提示独立性",),
    balance_controls=("高增量集合轮换拥有更少条目、更短描述或更晚出现",),
    scene_content_seeds={
        "夜间连续拉车门": "比较同角度低质重复画面与新增侧面清晰画面的信息增量。",
        "仓储搬运": "区分同一摄像头重复观测与不同点位形成的独立链路证据。",
        "望风协同": "识别同一连续片段中的多次同步出现并非多份独立支持。",
        "居民楼出入": "累积行为模式支持，但不越级确认角色或违法性质。",
    },
)

O32_SPEC = _spec(
    operator_id="O32_role_graph_critical_edge",
    name="角色关系图最小边",
    ability_axis="role_graph_critical_edge",
    goal="在主体关系图中识别支撑业务结论的必要关系边、方向及可替代路径。",
    required_question_shape="自然描述主体间协同、控制或传递关系，要求判断整体结论及其关键关系依据。",
    avoid="不要直接画图、标关键边或要求逐边分析；不要用角色数量制造难度。",
    evaluation_focus=("关系边方向是否正确", "关键边是否必要", "替代路径是否真正等价"),
    reasoning_object="带方向与功能语义的主体关系图",
    transformation="把原题主体列表改造成关系边效力不同、存在近似替代路径的角色图。",
    invariants=("关键关系均有题面行为依据", "共同出现不自动形成关系边", "整体结论依赖必要边或等价替代路径"),
    competition="竞争关系图共享多数节点与边，只在关键边方向、功能或替代效力上不同。",
    parent_obligations=("保留原题主体与业务结论", "保留原题关键协同行为"),
    reasoning_tasks=("恢复关系边", "判断边方向与功能", "识别必要边", "检查替代路径"),
    semantic_axes=(
        _axis("edge_semantics", "从行为事实恢复关系边的功能", ("cooccurrence_as_edge",), "共同出现不等于控制、协助或传递", ("行为事实", "关系语义")),
        _axis("edge_direction", "判断关系从谁指向谁", ("edge_direction_reversed",), "方向错误会改变角色与效力", ("实施者", "承受或受益者")),
        _axis("criticality_alternative", "判断边是否必要及替代路径是否等价", ("false_alternative_path",), "表面绕行不等于功能替代", ("目标功能", "候选路径")),
    ),
    target_errors=("critical_edge_missed", "noncritical_edge_treated_as_necessary", "role_direction_reversed", "cooccurrence_promoted_to_coordination"),
    excluded_errors=("实体身份冲突", "对象来源", "事件状态链"),
    shortcuts=("按中心节点猜关键边", "把共现当协同", "忽略边的方向与功能"),
    boundaries=("O19 侧重实体—行为角色绑定", "O13 侧重单个最小失效连接", "O29 侧重身份线索冲突"),
    positive_controls=("删除或反转真正必要边时，整体结论应改变",),
    negative_controls=("改变冗余或无关边时，整体结论不应改变",),
    adjacent_controls=("实体身份保持清晰，避免将关系错误混同身份错误",),
    surface_controls=("节点中心度、出场顺序、关系措辞强度不得泄露关键边",),
    balance_controls=("关键边轮换位于中心或边缘、早或晚、显式或间接的表面位置",),
)

O33_SPEC = _spec(
    operator_id="O33_cross_modal_support_boundary",
    name="跨模态支持边界",
    ability_axis="cross_modal_support_boundary",
    goal="对齐不同模态或来源的时间、对象和适用范围，处理冲突并给出融合材料允许的最强结论。",
    required_question_shape="自然组合视频、记录、信号、文本或检测结果，要求作出融合判断并说明材料共同支持的边界。",
    avoid="不要按模态逐项汇报；不要把来源多或技术名称复杂等同证据更强。",
    evaluation_focus=("来源范围是否对齐", "时间与实体是否正确绑定", "融合结论是否超过共同支持边界"),
    reasoning_object="跨模态来源—时段—实体—结论支持图",
    transformation="把原题单来源证据改造成范围互补、局部冲突且需对齐后才能融合的多来源材料。",
    invariants=("各来源能力与限制由题面给出", "跨模态材料必须指向同一时段或实体才能合并", "融合结论不强于最弱必要支持"),
    competition="竞争结论分别由表面一致的多来源数量和正确对齐后的共同支持范围驱动。",
    parent_obligations=("保留原题业务事实与结论", "保留每类来源原有的证据边界"),
    reasoning_tasks=("识别来源能力范围", "对齐时间与实体", "解释冲突或互补", "校准融合结论"),
    semantic_axes=(
        _axis("source_scope", "判断每种模态能直接支持什么", ("modal_scope_overreach",), "某模态不能观察的属性不得由其背书", ("来源能力", "观测范围")),
        _axis("cross_modal_alignment", "对齐来源的时间、对象与事件", ("cross_modal_misbinding",), "未对齐材料不能简单叠加", ("时间标记", "实体或事件标记")),
        _axis("fusion_boundary", "从互补与冲突材料形成最大可支持结论", ("fusion_overclaim",), "多源一致只增强共同可见部分", ("对齐事实", "结论要求")),
    ),
    target_errors=("source_count_treated_as_strength", "scope_mismatch_ignored", "time_alignment_ignored", "cross_source_entity_link_assumed", "conflict_silently_dropped", "fusion_promoted_beyond_evidence"),
    excluded_errors=("单来源观测可靠性", "纯跨层行动门槛", "仅做数值基线融合"),
    shortcuts=("按来源数量投票", "把时间相近当事件相同", "用技术来源名称替代能力范围"),
    boundaries=("O23 判断单项观测可靠性", "O27 判断证据到行动的跨层传导", "O18 判断统计基线范围", "O14 判断题面信息闭包"),
    positive_controls=("完成关键时间或实体对齐后，融合结论可以增强",),
    negative_controls=("加入无法观察目标属性的来源时，结论不应增强",),
    adjacent_controls=("各来源单项可靠性保持可用，让跨模态对齐与融合承担核心难度",),
    surface_controls=("模态数量、专业名称、呈现顺序和篇幅不得与正确结论绑定",),
    balance_controls=("决定性来源轮换承担更弱措辞、更少信息或较晚出现的表面角色",),
    scene_content_seeds={
        "涉黄直播": "对齐信号区域与视频中的人员、设备出入，限制角色结论。",
        "笑气线索": "区分容器外观、充气动作、地点与时间记录各自支持的范围。",
        "拉车门": "对齐不同摄像头中的外观与路径观察，并在冲突时降低结论。",
        "电动车": "融合动作视频、车辆轨迹和时间同步，控制协同、身份与违法结论边界。",
    },
)


NEW_OPERATOR_SPECS = (
    O19_SPEC,
    O20_SPEC,
    O21_SPEC,
    O22_SPEC,
    O23_SPEC,
    O24_SPEC,
    O25_SPEC,
    O26_SPEC,
    O27_SPEC,
    O28_SPEC,
    O29_SPEC,
    O30_SPEC,
    O31_SPEC,
    O32_SPEC,
    O33_SPEC,
)
