from .base import OperatorPromptSpec


SPEC = OperatorPromptSpec(
    operator_id="O11_unobserved_state_attribution",
    name="端点时序一致性",
    ability_axis="endpoint_temporal_consistency",
    goal=(
        "基于题面可见的入口/出口端点、时间窗和路径约束，判断不可见区间的候选假设是否时序一致，"
        "而不是推测盲区内真实发生了什么。"
    ),
    required_question_shape=(
        "题面完整给出可见端点、时间窗、路径或速度范围，并自然呈现两个都能解释部分端点事实的候选假设；"
        "只询问现有材料对不可见区间能够支持什么业务判断及依据。"
    ),
    avoid=(
        "不要补造盲区内事件、位置或动作，不要求推测真实未见状态；"
        "不要让整数大小、单个时长标签或“异常/正常”措辞直接决定答案。"
    ),
    default_evaluation_focus=(
        "是否把候选假设逐一映射到可见端点和时间窗",
        "是否依据路径与速度范围判断时序一致性",
        "是否拒绝把一致性判断升级为未见状态的事实认定",
    ),
    reasoning_object="可见端点、时间窗、路径约束与不可见区间候选假设之间的时序一致性",
    question_construction="给出可见端点、时间窗以及路径或速度范围；不补造未观察区间的事件，也不提供预计算路线。",
    content_transformation=(
        "保持题面可见事实不变，构造两个都能解释部分端点的候选假设；"
        "通过区间重叠、多出口或速度范围使一致性判断不能退化为整数大小比较。"
    ),
    invariants=(
        "所有可用端点、时间戳和路径约束均在题面中明确给出",
        "不新增任何盲区内已发生事件或真实状态",
        "候选假设面对相同端点和时间窗",
        "判断对象是时序一致性而非真实事件恢复",
    ),
    competition_structure=(
        "两个假设都解释部分端点事实，差异来自完整时序与路径约束能否同时满足；"
        "错误假设不能只因一个明显超时数字或标签被排除。"
    ),
    preserved_parent_obligations=(
        "保留父题根据已给观察组织证据而非补造事实的义务",
        "保留父题区分可支持判断与事实认定的结论边界",
    ),
    required_reasoning_tasks=(
        "把每个候选假设映射到入口、出口和时间窗",
        "结合路径与速度范围检查端点约束是否可同时满足",
        "将结论限制为题面端点支持的一致或不一致判断",
    ),
    target_error_taxonomy=(
        "endpoint_constraint_ignored",
        "temporal_inconsistency_missed",
        "unobserved_state_fabricated",
        "compatibility_treated_as_fact",
    ),
    excluded_error_taxonomy=(
        "action_vs_fact_rule_scope",
        "information_closure_validation",
        "multi_stage_event_chain_reconstruction",
    ),
    forbidden_shortcuts=(
        "补写盲区内真实事件或动作",
        "用单个整数大小直接决定答案",
        "公开端点映射步骤或候选假设的正确标签",
        "要求恢复完整不可见事件链",
    ),
    adjacent_operator_boundaries=(
        "两套明示业务规则的事实/处置适用范围归 O17",
        "题面是否补造事实属于 O14 的内容原则与后续校验职责",
        "多阶段事件链恢复不属于当前算子",
    ),
    positive_controls=(
        "一个候选假设同时满足端点、时间窗和路径约束，另一个只解释部分端点",
        "两个候选在局部时长上都合理，但只有一个满足全部区间约束",
    ),
    conclusion_invariant_negative_controls=(
        "改变非决定性端点描述后两个假设仍保持原一致性关系",
        "新增不影响路径可行性的观察，业务判断保持不变",
    ),
    adjacent_operator_controls=(
        "同样包含盲区但核心任务是两套规则范围映射的 O17 近邻",
        "需要补造未见事实才能作答、应判内容不成立的 O14 近邻",
    ),
    surface_swap_controls=(
        "交换候选假设顺序和出口名称不改变一致性答案",
        "等价改写时间单位与路径名称不改变约束关系",
    ),
    hidden_role_balance_controls=(
        "两个假设使用相近语义负载、具体度和表面合理性",
        "正确假设不独占精确数字或完整路径描述",
    ),
    semantic_economy=(
        "端点、时间窗和共同路径背景只写一次；各假设只保留影响不可见状态归因的差异。",
        "保留可回答所需的约束，不展开完整轨迹或替代路径清单。",
        "不得用更完整的路径说明或结论总结让某一假设显得安全。",
    ),
    prompt_recipe_version="semantic_economy_normal_v1",
    allowed_answer_shapes=(
        "自然业务判断加基于端点、时间窗和路径的开放式依据",
        "明确结论只涉及候选假设与已给事实的一致性",
    ),
    forbidden_answer_shapes=(
        "推测或断言盲区内真实发生的事件",
        "按题面预给映射表逐项填空",
        "仅比较时长数字大小",
    ),
)
